# Generated by Django 5.1.3 on 2024-12-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developers',
            fields=[
                ('developerid', models.IntegerField(primary_key=True, serialize=False)),
                ('developername', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'developers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Publishers',
            fields=[
                ('publisherid', models.IntegerField(primary_key=True, serialize=False)),
                ('publishername', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'publishers',
                'managed': False,
            },
        ),
    ]
