# Generated by Django 5.1.3 on 2024-12-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('gameid', models.IntegerField(primary_key=True, serialize=False)),
                ('gamename', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('coverurl', models.CharField(blank=True, max_length=512, null=True)),
                ('releasedate', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'game',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gamegenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'gamegenres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gameplayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'gameplayers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('genreid', models.IntegerField(primary_key=True, serialize=False)),
                ('genrename', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'genres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Platforms',
            fields=[
                ('platformid', models.IntegerField(primary_key=True, serialize=False)),
                ('platformname', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'platforms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userfollowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'userfollowers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userfollowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'userfollowing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('useremail', models.CharField(max_length=50, unique=True)),
                ('userpassword', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
