# Generated by Django 5.1.3 on 2024-12-06 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_game_gamegenres_gameplayers_genres_platforms_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developers',
            options={},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={},
        ),
        migrations.AlterModelOptions(
            name='gamegenres',
            options={},
        ),
        migrations.AlterModelOptions(
            name='gameplayers',
            options={},
        ),
        migrations.AlterModelOptions(
            name='genres',
            options={},
        ),
        migrations.AlterModelOptions(
            name='platforms',
            options={},
        ),
        migrations.AlterModelOptions(
            name='publishers',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userfollowers',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userfollowing',
            options={},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
    ]
